# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

image think1:
    "images/think1.png"
    0.5
    "images/think2.png"
    0.5
    repeat

image correct:
    "images/correct1.png"
    0.5
    "images/correct2.png"
    0.5
    repeat

image incorrect:
    "images/incorrect1.png"
    0.5
    "images/incorrect2.png"
    0.5
    repeat

image brainstorm:
    zoom 2.45
    "images/brainstorm.png"

label game_start2:
    # Initialize global variables for use in the game.
    default draggable = ""
    default droppable = ""
    #default is_right = False
    default current_rationale = ""
    
    init python:

        store.rationales = { # New dictionary to store all fact explanations
            # --- PROBLEM 1: Air pollution and traffic congestion ---
            "CorrectBlock1": "CORRECT! ENSO encourages Students and Faculty alike to use or rent Bicycles through BPSU Padyak, you can borrow bike at Medina!",
            "P1WrongBlock1": "Not quite. Implementing a **congestion fee** is purely punitive and doesn't offer a sustainable alternative like bicycling.",
            "P1WrongBlock2": "No. **Smog-eating billboards** treat the symptom (pollution) but don't address the root cause (traffic volume).",
            "P1WrongBlock3": "Nope. The **No Idling** rule helps, but Rent-A-Bike provides a complete alternative to eliminate the engine entirely.",
            "P1WrongBlock4": "Wrong. **Air quality research** is assessment, not an action/solution to reduce the traffic volume itself.",

            # --- PROBLEM 2: Excessive single-use cups/bottles ---
            "CorrectBlock2": "CORRECT! The discount incentivizes a positive behavioral change (REUSE) by rewarding students for reducing single-use waste at the source.",
            "P2WrongBlock1": "Incorrect. A **Plastic Tax** can deter use, but it's less positive than rewarding the re-use of personal tumblers.",
            "P2WrongBlock2": "Not the best. **Water refilling stations** are good, but they don't solve the waste generated by canteens selling coffee and soda in disposable cups.",
            "P2WrongBlock3": "Wrong. **Composting** deals with organic waste, not the plastic cups and lids used for cold drinks.",
            "P2WrongBlock4": "No. **Banning outside items** is overly restrictive and complex to enforce.",

            # --- PROBLEM 3: Overflowing trash bins ---
            "CorrectBlock3": "CORRECT! Color-Coded Bins are a soon to be implemented here at Treyd that aims to reduce the volume of general waste that causes bins to overflow.",
            "P3WrongBlock1": "Wrong. **Increasing the size** of bins just delays the overflow and ignores the real solution: reducing the volume sent to the landfill through recycling.",
            "P3WrongBlock2": "Not quite. **Collecting trash twice daily** increases operational costs but doesn't fix the systemic problem of high, un-diverted trash volume.",
            "P3WrongBlock3": "No. **Littering fines** address irresponsible disposal, not the systematic problem of overall waste volume.",
            "P3WrongBlock4": "Incorrect. A **Waste-to-Energy project** is an expensive, end-of-life solution, whereas Color-Coded Bins tackle the issue at the source.",

            # --- PROBLEM 4: Intense campus heat and lack of shaded walkways ---
            "CorrectBlock4": "CORRECT! for the Dinalupihan campus--Gender-neutral restrooms are implemented to provide inclusivity and ease for individuals with diverse identities",
            "P4WrongBlock1": "Wrong. **Reflective white paint** helps cool the pavement, but planting provides better shade and evaporative cooling for walkways.",
            "P4WrongBlock2": "Not effective. **Mist sprayers** use water and electricity and offer temporary relief, unlike the lasting shade from plants.",
            "P4WrongBlock3": "No. **Changing class schedules** avoids the heat, but it doesn't solve the environmental problem of the hot campus landscape itself.",
            "P4WrongBlock4": "Incorrect. **Geothermal cooling** is extremely expensive and complex technology for addressing surface-level heat and shade for pedestrians.",

            # --- PROBLEM 5: Lack of Gender Perspective in environmental programs ---
            "CorrectBlock5": "CORRECT. ENSO partners with multiple organizations such as SM to turn waste collected from the campus into cash.",
            "P5WrongBlock1": "Wrong. **Gender Quotas** are a high-level policy often seen as tokenism, whereas training ensures genuine understanding and inclusion.",
            "P5WrongBlock2": "No. Research on **women in environmental history** is academic and doesn't translate into immediate, actionable policy changes for ENSO's programs.",
            "P5WrongBlock3": "Incorrect. **Gender-Neutral Restrooms** are an infrastructure/security issue, not a policy solution that integrates the GAD perspective into environmental programs.",
            "P5WrongBlock4": "Not quite. A forum on **ecofeminism theory** is too academic for a general advocacy group. Training offers practical tools.",
            
            "current_rationale": "" # New key for the rationale dictionary (optional, but good practice)
        }

        # This function handles the logic after any drag-and-drop occurs.
        # It MUST use 'store.' to update game-level variables used by the screen.
        def drag_placed2(drags, drop):
            if not drop:
                return

            store.draggable1 = drags[0].drag_name
            store.droppable1 = drop.drag_name
            store.current_rationale = store.rationales.get(store.draggable1, "Error: Rationale not found. Key: %s" % store.draggable1)


            # This determines if the answer was correct, used later to update the score.
            if (store.draggable1 == "CorrectBlock1" and store.droppable1 == "Problem1") or \
            (store.draggable1 == "CorrectBlock2" and store.droppable1 == "Problem2") or \
            (store.draggable1 == "CorrectBlock3" and store.droppable1 == "Problem3") or \
            (store.draggable1 == "CorrectBlock4" and store.droppable1 == "Problem4") or \
            (store.draggable1 == "CorrectBlock5" and store.droppable1 == "Problem5"):
                store.is_correct2 = True
            else:
                store.is_correct2 = False

            # 2. Update blocks and advance to the next problem set (always advance logic).
            
            # Problem 1 check: If a block from P1 (correct or wrong) was dragged.
            if (store.draggable1 == "CorrectBlock1") or \
            (store.draggable1.startswith("P1WrongBlock")):
                
                # Hide all elements for Problem 1
                store.Problem1_hide = True
                store.CorrectBlock1_hide = True
                store.P1WrongBlock1_hide = True
                store.P1WrongBlock2_hide = True
                store.P1WrongBlock3_hide = True
                store.P1WrongBlock4_hide = True

                # Show all elements for Problem 2
                store.Problem2_hide = False
                store.CorrectBlock2_hide = False
                store.P2WrongBlock1_hide = False
                store.P2WrongBlock2_hide = False
                store.P2WrongBlock3_hide = False
                store.P2WrongBlock4_hide = False

            # Problem 2 check
            elif (store.draggable1 == "CorrectBlock2") or \
                (store.draggable1.startswith("P2WrongBlock")):

                # Hide all elements for Problem 2
                store.Problem2_hide = True
                store.CorrectBlock2_hide = True
                store.P2WrongBlock1_hide = True
                store.P2WrongBlock2_hide = True
                store.P2WrongBlock3_hide = True
                store.P2WrongBlock4_hide = True

                # Show all elements for Problem 3
                store.Problem3_hide = False
                store.CorrectBlock3_hide = False
                store.P3WrongBlock1_hide = False
                store.P3WrongBlock2_hide = False
                store.P3WrongBlock3_hide = False
                store.P3WrongBlock4_hide = False
            
            # Problem 3 check
            elif (store.draggable1 == "CorrectBlock3") or \
                (store.draggable1.startswith("P3WrongBlock")):

                # Hide all elements for Problem 3
                store.Problem3_hide = True
                store.CorrectBlock3_hide = True
                store.P3WrongBlock1_hide = True
                store.P3WrongBlock2_hide = True
                store.P3WrongBlock3_hide = True
                store.P3WrongBlock4_hide = True

                # Show all elements for Problem 4
                store.Problem4_hide = False
                store.CorrectBlock4_hide = False
                store.P4WrongBlock1_hide = False
                store.P4WrongBlock2_hide = False
                store.P4WrongBlock3_hide = False
                store.P4WrongBlock4_hide = False

            # Problem 4 check
            elif (store.draggable1 == "CorrectBlock4") or \
                (store.draggable1.startswith("P4WrongBlock")):

                # Hide all elements for Problem 4
                store.Problem4_hide = True
                store.CorrectBlock4_hide = True
                store.P4WrongBlock1_hide = True
                store.P4WrongBlock2_hide = True
                store.P4WrongBlock3_hide = True
                store.P4WrongBlock4_hide = True

                # Show all elements for Problem 5
                store.Problem5_hide = False
                store.CorrectBlock5_hide = False
                store.P5WrongBlock1_hide = False
                store.P5WrongBlock2_hide = False
                store.P5WrongBlock3_hide = False
                store.P5WrongBlock4_hide = False

            # Problem 5 check (End of game state)
            elif (store.draggable1 == "CorrectBlock5") or \
                (store.draggable1.startswith("P5WrongBlock")):
                
                # Hide all elements for Problem 5
                store.Problem5_hide = True
                store.CorrectBlock5_hide = True
                store.P5WrongBlock1_hide = True
                store.P5WrongBlock2_hide = True
                store.P5WrongBlock3_hide = True
                store.P5WrongBlock4_hide = True
            
            # Return True to signal Ren'Py to stop the drag-and-drop interaction
            return True
    
#---
label Minigame2:
    # Set default values for all variables used in the game.
    default correct1 = 0
    default incorrect1 = 0
    default Problem1_hide = False
    default Problem2_hide = True
    default Problem3_hide = True
    default Problem4_hide = True
    default Problem5_hide = True
    default CorrectBlock1_hide = False
    default CorrectBlock2_hide = True
    default CorrectBlock3_hide = True
    default CorrectBlock4_hide = True
    default CorrectBlock5_hide = True
    default P1WrongBlock1_hide = False
    default P1WrongBlock2_hide = False
    default P1WrongBlock3_hide = False
    default P1WrongBlock4_hide = False
    default P2WrongBlock1_hide = True
    default P2WrongBlock2_hide = True
    default P2WrongBlock3_hide = True
    default P2WrongBlock4_hide = True
    default P3WrongBlock1_hide = True
    default P3WrongBlock2_hide = True
    default P3WrongBlock3_hide = True
    default P3WrongBlock4_hide = True
    default P4WrongBlock1_hide = True
    default P4WrongBlock2_hide = True
    default P4WrongBlock3_hide = True
    default P4WrongBlock4_hide = True
    default P5WrongBlock1_hide = True
    default P5WrongBlock2_hide = True
    default P5WrongBlock3_hide = True
    default P5WrongBlock4_hide = True

    scene brainstorm

    play music "audio/particle.mp3" loop fadein 2.5

    show think1

    "Time to Brainstorm!"

    "Anong intervention plan ang na-implement ng ENSO dito sa BPSU para ma-address ang mga sumusunod na suliranin?"

    call screen BrainstormScreen

    jump game2_loop

#---
label game2_loop:

    if is_correct2:
        $ correct1 += 1
        show correct
        "That's right!"
        hide correct
        "[store.current_rationale]"

    else:
        $ incorrect1 += 1
        show incorrect
        "Hmmmm, wala naman atang ganong platapormang na-establish."
        hide incorrect
    
        # This line is correct and will display the text once the Python function updates the variable.
        "[store.current_rationale]"

    # Check if the game is over (5 total attempts required).
    if correct1 + incorrect1 >= 5:
        jump matchCheck

    # Re-call the screen with the new variable states.
    call screen BrainstormScreen
    jump game2_loop

#---
label matchCheck:
    hide screen BrainstormScreen 
    image win = "win.png"
    image lose = "lose.png"

    if correct1 == 5:
        show win
        "You matched each corresponding platforms correctly! You win!"
        $ eco_meter += 10
    elif correct1 >= 3:
        show win
        "You're getting there!"
    else:
        show lose
        "You made a mistake. Better luck next time!"

    jump faculty_scene 

#---
screen BrainstormScreen:
    tag BrainstormScreen 

    text "Think of appropriate solutions to the Problem!":
        pos (70, 600)
        bold True
        color "#1d390066"

    # Score Display
    text "correct = [correct1]":
        pos (70, 650)
        bold True
        color "#1d390066"

    text "wrong = [incorrect1]":
        pos (70, 690)
        bold True
        color "#1d390066"

    draggroup:
        # --- DROPPABLE TARGETS (Problems 1-5) ---
        
        if not Problem1_hide:
            drag:
                drag_name "Problem1"
                xpos 100
                ypos 100
                child "images/Problem1.png"
                draggable False
                droppable True
                drag_raise False

        if not Problem2_hide:
            drag:
                drag_name "Problem2"
                xpos 100
                ypos 100
                child "images/Problem2.png"
                draggable False
                droppable True
                drag_raise False
        
        if not Problem3_hide:
            drag:
                drag_name "Problem3"
                xpos 100
                ypos 100
                child "images/Problem3.png"
                draggable False
                droppable True
                drag_raise False
    
        if not Problem4_hide:
            drag:
                drag_name "Problem4"
                xpos 100
                ypos 100
                child "images/Problem4.png"
                draggable False
                droppable True
                drag_raise False

        if not Problem5_hide:
            drag:
                drag_name "Problem5"
                xpos 100
                ypos 100
                child "images/Problem5.png"
                draggable False
                droppable True
                drag_raise False
    
        # --- DRAGGABLE BLOCKS (Correct Blocks) ---
        
        if not CorrectBlock1_hide:
            drag:
                drag_name "CorrectBlock1"
                xpos 1000
                ypos 100
                child "images/CorrectBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not CorrectBlock2_hide:
            drag:
                drag_name "CorrectBlock2"
                xpos 900
                ypos 100
                child "images/CorrectBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not CorrectBlock3_hide:
            drag:
                drag_name "CorrectBlock3"
                xpos 900
                ypos 100
                child "images/CorrectBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not CorrectBlock4_hide:
            drag:
                drag_name "CorrectBlock4"
                xpos 1000
                ypos 100
                child "images/CorrectBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not CorrectBlock5_hide:
            drag:
                drag_name "CorrectBlock5"
                xpos 800
                ypos 100
                child "images/CorrectBlock5.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True
        
        # --- DRAGGABLE BLOCKS (Wrong Blocks) ---
        
        if not P1WrongBlock1_hide:
            drag:
                drag_name "P1WrongBlock1"
                xpos 1000
                ypos 150
                child "images/P1WrongBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P1WrongBlock2_hide:
            drag:
                drag_name "P1WrongBlock2"
                xpos 1000
                ypos 200
                child "images/P1WrongBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P1WrongBlock3_hide:
            drag:
                drag_name "P1WrongBlock3"
                xpos 920
                ypos 100
                child "images/P1WrongBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P1WrongBlock4_hide:
            drag:
                drag_name "P1WrongBlock4"
                xpos 890
                ypos 140
                child "images/P1WrongBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True
        
        # P2 Wrong Blocks
        if not P2WrongBlock1_hide:
            drag:
                drag_name "P2WrongBlock1"
                xpos 1000
                ypos 100
                child "images/P2WrongBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P2WrongBlock2_hide:
            drag:
                drag_name "P2WrongBlock2"
                xpos 1000
                ypos 100
                child "images/P2WrongBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P2WrongBlock3_hide:
            drag:
                drag_name "P2WrongBlock3"
                xpos 1000
                ypos 100
                child "images/P2WrongBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P2WrongBlock4_hide:
            drag:
                drag_name "P2WrongBlock4"
                xpos 1000
                ypos 100
                child "images/P2WrongBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True
        
        # P3 Wrong Blocks
        if not P3WrongBlock1_hide:
            drag:
                drag_name "P3WrongBlock1"
                xpos 1000
                ypos 100
                child "images/P3WrongBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P3WrongBlock2_hide:
            drag:
                drag_name "P3WrongBlock2"
                xpos 1000
                ypos 100
                child "images/P3WrongBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P3WrongBlock3_hide:
            drag:
                drag_name "P3WrongBlock3"
                xpos 1000
                ypos 100
                child "images/P3WrongBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P3WrongBlock4_hide:
            drag:
                drag_name "P3WrongBlock4"
                xpos 1000
                ypos 100
                child "images/P3WrongBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True
        
        # P4 Wrong Blocks
        if not P4WrongBlock1_hide:
            drag:
                drag_name "P4WrongBlock1"
                xpos 1000
                ypos 100
                child "images/P4WrongBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P4WrongBlock2_hide:
            drag:
                drag_name "P4WrongBlock2"
                xpos 1000
                ypos 100
                child "images/P4WrongBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P4WrongBlock3_hide:
            drag:
                drag_name "P4WrongBlock3"
                xpos 1000
                ypos 100
                child "images/P4WrongBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P4WrongBlock4_hide:
            drag:
                drag_name "P4WrongBlock4"
                xpos 1000
                ypos 100
                child "images/P4WrongBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True
        
        # P5 Wrong Blocks (Corrected drag_name)
        if not P5WrongBlock1_hide:
            drag:
                drag_name "P5WrongBlock1"
                xpos 1000
                ypos 100
                child "images/P5WrongBlock1.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P5WrongBlock2_hide:
            drag:
                drag_name "P5WrongBlock2"
                xpos 1000
                ypos 100
                child "images/P5WrongBlock2.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P5WrongBlock3_hide:
            drag:
                drag_name "P5WrongBlock3"
                xpos 1000
                ypos 100
                child "images/P5WrongBlock3.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True

        if not P5WrongBlock4_hide:
            drag:
                drag_name "P5WrongBlock4"
                xpos 1000
                ypos 100
                child "images/P5WrongBlock4.png"
                draggable True
                droppable False
                dragged drag_placed2
                drag_raise True